Cypress.on('uncaught:exception', (err, runnable) => {
    // Impede que o Cypress falhe o teste por erro nÃ£o capturado
    return false;
});
